import Head from 'next/head';
import Header from '../components/Header';
import ContrastContainer from '../components/ContrastContainer';
import TwoColumnLayout from '../components/TwoColumnLayout';
import ExternalLink from '../components/ExternalLink';
import Icon from '../components/Icon';
import Footer from '../components/Footer';

const Home = () => {
  const heading = 'Pawel Swies — Web Developer';
  return (
    <>
      <Head>
        <title>{heading}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h1 className="visually-hidden">{heading}</h1>
        <p>Hey, I&apos;m Pawel Swies. I&apos;m a web developer interested in UI design and development, UX and design systems.</p>
        <p>
          I love to work with React, but I&apos;m always dabbling with other tech like Svelte. You can view some of my work on{' '}
          <ExternalLink link="https://codesandbox.io/u/pav-swies" highlighted>
            <Icon icon="codesandbox" />
          </ExternalLink>{' '}
          and{' '}
          <ExternalLink link="https://github.com/pav-swies" highlighted>
            <Icon icon="github" />
          </ExternalLink>
          .
        </p>
        <p>
          You can reach out to me on{' '}
          <ExternalLink link="https://twitter.com/p_swies" highlighted>
            <Icon icon="twitter" hiddenText="Twitter" />
          </ExternalLink>{' '}
          or{' '}
          <ExternalLink link="https://www.linkedin.com/in/pawel-swies-63608016b/" highlighted>
            <Icon icon="linkedin" hiddenText="LinkedIn" />
          </ExternalLink>
          .
        </p>
      </Header>
      <main>
        <ContrastContainer>
          <TwoColumnLayout title="Experience" sticky>
            <p>
              I specialise in building robust and accessible user interfaces. I’ve been involved in building UI’s for many projects across many industries, including Uber for Business and Santander.
            </p>
          </TwoColumnLayout>
          <TwoColumnLayout title="Huler" subtitle="2021 — Present" sticky>
            <p>
              Lorem ipsum dolor sit, amet consectetur <Icon icon="github" hiddenText="GitHub" /> adipisicing elit.
            </p>
            <ul>
              <li>Lorem, ipsum.</li>
              <li>Lorem, ipsum.</li>
              <li>Lorem, ipsum.</li>
            </ul>
          </TwoColumnLayout>
          <TwoColumnLayout title="Don't be Shy" subtitle="2020 — 2021" sticky>
            <p>Responsible for working closely with the development and creative team to transform static designs into fully interactive websites for companies such as Uber for Business.</p>
            <ul>
              <li>
                <p>
                  Involved in building{' '}
                  <ExternalLink link="https://resourced.prometheanworld.com/about-technology-education-industry-report-2019/#landing-about">The State of Technology in Education </ExternalLink>{' '}
                  2019/2020 Report, which used data from more than 2,000 educators across the UK.
                </p>
              </li>
              <li>Lorem, ipsum.</li>
              <li>Lorem, ipsum.</li>
            </ul>
          </TwoColumnLayout>
          <TwoColumnLayout title="MMU" icon="graduation" subtitle="2017 — 2020" sticky>
            <p>I graduated from Manchester Metropolitan University with a First-Class degree in Digital Media and Communications.</p>
          </TwoColumnLayout>
        </ContrastContainer>
      </main>
      <Footer />
    </>
  );
};

export default Home;
